### ISSUE TITLE
3.2.1.121注入后，连不上

### ISSUE THREAD

**Issue by ActivePeter** [cixingguangming55555/wechat-bot#160]
Traceback (most recent call last):
  File "e:\pa_files\bb_review_robot\wechat-bot\client\python\httpclient.py", line 189, in <module>
    test()
  File "e:\pa_files\bb_review_robot\wechat-bot\client\python\httpclient.py", line 175, in test
    print(wb.get_personal_info())
  File "e:\pa_files\bb_review_robot\wechat-bot\client\python\httpclient.py", line 170, in get_personal_info
    return self.send(uri, data)
  File "e:\pa_files\bb_review_robot\wechat-bot\client\python\httpclient.py", line 45, in send
    res = requests.post(url, json={'para': base_data}, timeout=5)
  File "E:\pa_files\bb_review_robot\virtual\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "E:\pa_files\bb_review_robot\virtual\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\pa_files\bb_review_robot\virtual\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\pa_files\bb_review_robot\virtual\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\pa_files\bb_review_robot\virtual\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5555): Max retries exceeded with url: /api/get_personal_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016A04248F10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by Sencc** [comment]
再重新打开注入试试

**Comment by ActivePeter** [comment]
> 再重新打开注入试试

也不行，我试了好多下

**Comment by jxyk2007** [comment]
没有问题，注意步骤，打开注入器---启动微信----注入dll  c:\temp\wechat\这个文件夹就会生成了

**Comment by jxyk2007** [comment]
``node http-3.2.1.121.js``  获取微信信息

**Comment by ActivePeter** [comment]
> `node http-3.2.1.121.js` 获取微信信息
![image](https://user-images.githubusercontent.com/8100696/187045594-f220ef98-d3f9-48be-a156-80e55660e048.png)
![image](https://user-images.githubusercontent.com/8100696/187045609-9f04763b-255d-4083-b4fd-a077f353f837.png)

**Comment by cixingguangming55555** [comment]
第一：微信版本要和DLL版本要一致，第二：按照操作步骤一步一步来，第三，必须要懂一门开发语言，然后找对应客户端测试验证

**Comment by shirubei** [comment]
3.2.1 和 3.3.0我一直都是可以的
