### ISSUE TITLE
每次重新启动微信，都需要注入吗？

### ISSUE THREAD

**Issue by helai78** [cixingguangming55555/wechat-bot#164]
每次重新启动微信，都需要注入吗？
如果不注入,就会显示：计算机拒绝
每次注入后，就功能正常

**Comment by helai78** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Program Files\Python37\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Program Files\Python37\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python37\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "C:\Program Files\Python37\lib\http\client.py", line 972, in send
    self.connect()
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000028F0FB2F588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by helai78** [comment]
但是一旦注入后，功能就正常了

**Comment by JoffreyN** [comment]
当然需要

**Comment by cixingguangming55555** [comment]
每次都需要重新注入的
